# Run cypress tests
name: Cypress tests
on:
  push:
    branches-ignore: [ master, staging ]

jobs:
  cypress-run:
    name: Cypress run for trilateral
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          project: ./app/
          spec: tests/e2e/specs/indicators_trilateral.js
          config: baseUrl=https://eodash-testing.eox.at/${GITHUB_REF##*/}/
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
